#!/usr/bin/env python3
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
dist = root / "dist"
output = root / "src" / "html-assets.ts"

spa = (dist / "index.html").read_text(encoding="utf-8")
login = (dist / "login.html").read_text(encoding="utf-8")

output.write_text(
    "\n".join(
        [
            "// Auto-generated by scripts/embed-html.py - do not edit manually",
            f"export const SPA_HTML = {json.dumps(spa)};",
            f"export const LOGIN_HTML = {json.dumps(login)};",
            "",
        ]
    ),
    encoding="utf-8",
)

print(f"Generated {output.relative_to(root)} ({output.stat().st_size} bytes)")
